language: php

env:
  - TRAVIS_NODE_VERSION="4"

addons:
  apt:
    packages:
      - pyflakes

before_script:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - npm install

script:
  - node parse.js
